sudo: required
language: generic
dist: trusty # Ubuntu 14.04
services: docker # Enables docker

script:
- wget https://raw.githubusercontent.com/blang/latex-docker/master/latexdockercmd.sh
- chmod +x latexdockercmd.sh
- ./latexdockercmd.sh make

before_deploy:
  - git config --local user.name "Chombo Club Admin"
  - git config --local user.email "admin@chombo.club"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y-%m-%d')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file:
    - ./*.pdf
    - ./*.docx
    - ./*.tex
  skip_cleanup: true
  overwrite: true
  on:
    branch: master
    tags: true