language: generic
os: linux
dist: jammy
services: docker

before_install:
- sudo apt-get update

install:
- sudo apt-get install -y texlive-latex-extra texlive-lang-polish texlive-generic-recommended texlive-fonts-recommended texlive-fonts-extra poetry make

script:
- make all

before_deploy:
  - git config --local user.name "Chombo Club Admin"
  - git config --local user.email "admin@chombo.club"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y-%m-%d')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  token: $GITHUB_TOKEN
  name: Statut $(date +'%d-%m-%Y')
  file_glob: true
  file:
    - ./build/statut.pdf
    - ./build/statut.tex
  skip_cleanup: true
  overwrite: true
  on:
    branch: master
