[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
PyYAML = "^6.0"
pydantic = "^2.10.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
